### PR TITLE
Updated README.md to include trouble shoot information

### PR DESCRIPTION
**Pull request by johnhu84**
@juwai/frontend, @juwai/site-dev, @mryder, @arkhi - Updated readme to include troubleshoot information

### CODE REVIEW

**Comment by HouCoder** [comment]
This because sometimes the Ruby gem is blocked in China by GFW, I think we can make the troubleshoot more simply, just add:

``` markdown

### Troubleshoot

The RubyGems Mirror is blocked in China by GFW, please consider use [Taobao RubyGems Mirror](https://ruby.taobao.org/index_en.html).
```

**Comment by HouCoder** [comment]
I finished reviewing.

**Comment by johnhu84** [comment]
@juwai/frontend, @HouCoder , @arkhi - Please check again, thanks

**Comment by arkhi** [comment]
Useful tip. Thanks @johnhu84. Merging…

**Pull request merged**
